---
# File: tasks/install.yml - package installation tasks for vault

- name: OS packages
  become: true
  package:
    name: "{{ vault_os_packages }}"
    state: present
    update_cache: true
  tags: installation

# Temporary place for one-off version diff packages, etc.
- name: OS packages diff (Debian)
  become: true
  package:
    name: "libcap2-bin"
    state: present
  tags: installation
  when:
    - ansible_distribution == "Debian"
    - (ansible_distribution_version == 'buster/sid') or (ansible_distribution_version is version(8.5, '>'))

- name: "Download Vault (local) → {{ vault_zip_url }}"
  get_url:
    url: "{{ vault_zip_url }}"
    dest: "{{ role_path }}/files/{{ vault_pkg }}"
    checksum: "sha256:{{ vault_sha256.stdout }}"
    timeout: "42"
  become: "{{ vault_privileged_install }}"
  run_once: true
  tags: installation
  when: not vault_package.stat.exists | bool
  delegate_to: 127.0.0.1

- name: Unarchive Vault (local)
  unarchive:
    src: "{{ role_path }}/files/{{ vault_pkg }}"
    dest: "{{ role_path }}/files/"
    creates: "{{ role_path }}/files/vault"
  become: "{{ vault_privileged_install }}"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1

- name: Install Vault
  become: true
  copy:
    src: "{{ role_path }}/files/vault"
    dest: "{{ vault_bin_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"
  notify: Restart vault
  tags: installation

- name: Cleanup (local)
  file:
    path: "{{ item }}"
    state: "absent"
  become: "{{ vault_privileged_install }}"
  with_fileglob: "{{ role_path }}/files/vault"
  run_once: true
  tags: installation
  delegate_to: 127.0.0.1



 - name: Create vault server configuration
    template:
      src: vault.hcl.j2
      dest: "{{ vault_conf }}"
      owner: "{{ vault_user }}"
      group: "{{ vault_group }}"
      mode: 0640

  - name: Create vault systemd service config
    template:
      src: vault.service.j2
      dest: "/etc/systemd/system/{{ vault_service }}.service"
      owner: vault
      group: vault
      mode: 0664
      force: no

  - name: Start and enable vault systemd service
    systemd:
      name: "{{ vault_service }}"
      daemon_reload: yes
      state: started
      enabled: yes

  - name: Set VAULT_ADDR listener in profile
    template:
      src: profile.sh.j2
      dest: /etc/profile.d/vault.sh
      owner: root
      group: root
      mode: 0755
