---
#install vault

  - name: Install dependencies
    apt:
      pkg:
      - unzip
      - gnupg-utils
      - build-essential
      - libsqlite3-dev
      - libxml2-dev
      - libldns-dev
      - libbotan-2-dev

  - name: Download Checksums
    ansible.builtin.get_url:
      url: "{{ vault_checksums_url }}"
      dest: "{{ vault_checksums_file }}"

  - name: Saving checksum
    ansible.builtin.shell: cat '{{ vault_checksums_file }}' | grep '{{ vault_file }}' | cut -c 1-64
    register: vault_checksum

  - name: Download Vault
    get_url:
      url: "{{ vault_src }}"
      dest: "{{ vault_download_path }}"
      mode: 0660
      checksum: "sha256:{{ vault_checksum.stdout }}"

  - name: Extract vault.zip
    ansible.builtin.unarchive:
      src: "{{ vault_download_path }}"
      dest: "{{ vault_bin_path }}"
      remote_src: true
      mode: 0660

  
  - name: Clean Up
    file:
      state: absent
      path: "{{ item }}"
    with_items:
      - "{{ vault_checksums_file }}"
      - "{{ vault_download_path }}"

  - name: Create group vault
    group:
      name: "{{ vault_group }}"
      gid: "{{ vault_gid }}"
      state: present

  - name: Create user vault
    user:
      name: "{{ vault_user }}"
      group: "{{ vault_group }}"
      uid: "{{ vault_gid }}"
      shell: /sbin/nologin
      system: yes
      
  - name: Create content & directory
    file:
      state: directory
      path: "{{ item }}"
      owner: "{{ vault_user }}"
      group: "{{ vault_group }}"
    with_items:
      - "{{ vault_raft_path }}"
      
  - name: Create conf
    file:
      state: touch
      owner: vault
      group: vault
      path: "{{ vault_conf }}"

#  - name: Install PIP3
#    package:
#      name: python3-pip
#      state: present

# - name: Upgrade PIP
#   pip:
#     name: pip
#     state: latest

# - name: Install python OpenSSL dependencies
#   pip:
#     name: "{{ item }}"
#   loop:
#     - "pyOpenSSL"

# - name: Generate OpenSSL private key pem file
#   openssl_privatekey:
#     path: "{{ vault_privkey }}"

# - name: Generate an OpenSSL CSR
#   openssl_csr:
#     path: "{{ vault_csr }}"
#     privatekey_path: "{{ vault_privkey }}"
#     common_name: "{{ vault_cn }}"
#     country_name: "{{ vault_cc }}"
#     organization_name: "{{ vault_on }}"

#  - name: Generate a Self-Signed OpenSSL certificate
#    openssl_certificate:
#      path: "{{ vault_certfile }}"
#      privatekey_path: "{{ vault_privkey }}"
#      csr_path: "{{ vault_csr }}"
#      provider: selfsigned

#  - name: Adjust certificate files ownerships
#    file:
#      path: "{{ vault_certs }}"
#      owner: "{{ vault_user }}"
#      group: "{{ vault_group }}"
#      state: directory
#      recurse: yes
#      mode: 0664

# - name: Remove python OpenSSL dependencies
#   pip:
#     name: "{{ item }}"
#     state: absent
#   loop:
#     - "pyOpenSSL"

  - name: Create vault server configuration
    template:
      src: vault.hcl.j2
      dest: "{{ vault_conf }}"
      owner: "{{ vault_user }}"
      group: "{{ vault_group }}"
      mode: 0640

  - name: Create vault systemd service config
    template:
      src: vault.service.j2
      dest: "/etc/systemd/system/{{ vault_service }}.service"
      owner: root
      group: root
      mode: 0664
      force: no

  - name: Start and enable vault systemd service
    systemd:
      name: "{{ vault_service }}"
      daemon_reload: yes
      state: started
      enabled: yes
 
  - name: Set VAULT_ADDR listener in profile
    template:
      src: profile.sh.j2
      dest: /etc/profile.d/vault.sh
      owner: root
      group: root
      mode: 0755
