---
# defaults file for anisble-role-vault-init

vault_addr: "10.0.101.13"
vault_port: 8200
vault_user: "vault"
vault_group: "vault"
vault_service: "vault"
vault_keysfile: "~/.hashicorp_vault_keys.json"
